steps:
#- id: Build Image
#  name: 'gcr.io/cloud-builders/docker'
#  args: ['build', '--tag=us-docker.pkg.dev/benhuston-abm/cloud-build-hybrid-container-registry:v0.1.0', '--file=Dockerfile', '.']
#- id: Push Image
#  name: 'gcr.io/cloud-builders/docker'
#  args: ['push', 'us-docker.pkg.dev/benhuston-abm/cloud-build-hybrid-container-registry:v0.1.0']
- id: Deploy to Anthos cluster
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    set -x && \
    export KUBECONFIG="$(pwd)/gateway-kubeconfig" && \
    gcloud container hub memberships get-credentials ${_CLUSTER_NAME} && \
    kubectl get pod -A && \
    kubectl --kubeconfig gateway-kubeconfig apply -f deployment.yaml
options:
  # Overrides the default value of 60 GB
  diskSizeGb: '10'
  anthosCluster:
    membership: projects/$PROJECT_NUMBER/locations/global/memberships/${_CLUSTER_NAME}
substitutions:
  _CLUSTER_NAME: gke-cluster-001 # default value